version: '3.8'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - db.env
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
